version: '3.8'

services:
  # Database PostgreSQL 
  db:
    image: postgres:15-alpine
    container_name: edtech_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edtech_user -d edtech_mvp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.yaml
    container_name: edtech_api
    ports:
      - "8080:8080"
    environment:
      # ENV PER IL DB, CI VUOLE DB NON LOCALHOST PERCHÉ È IL NOME SERVIZIO DOCKER 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
      # Queste env controllale tu, prese da chatgpt
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate 
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      
      # Questo 
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
      
    depends_on:
      db:
        condition: service_healthy
        
    # Per sviluppo hot reload senza volumi app poi vediamo
    # volumes:
    #   - ./backend/src:/app/src

volumes:
  postgres_data: